[project]
name = "Dagster_Test"
requires-python = ">=3.10"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-webserver",
    "plotly",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
